// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDauZ_xpjkquTq6TtunPQz6sPdqzv5nagU',
    appId: '1:60097487307:web:8e0304aee212f0c04c964e',
    messagingSenderId: '60097487307',
    projectId: 'campfood-6e14c',
    authDomain: 'campfood-6e14c.firebaseapp.com',
    storageBucket: 'campfood-6e14c.firebasestorage.app',
    measurementId: 'G-LDVS45WCHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGunRmzsUUWUjfxGV9Y3Flj-XQMBPBhTI',
    appId: '1:60097487307:android:8d6f367626f800894c964e',
    messagingSenderId: '60097487307',
    projectId: 'campfood-6e14c',
    storageBucket: 'campfood-6e14c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBclcz7xbUW5NIwNPuMtwdOK44_OSgDyg8',
    appId: '1:60097487307:ios:5a9bd57fdc83d2834c964e',
    messagingSenderId: '60097487307',
    projectId: 'campfood-6e14c',
    storageBucket: 'campfood-6e14c.firebasestorage.app',
    iosBundleId: 'com.campfood.campfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBclcz7xbUW5NIwNPuMtwdOK44_OSgDyg8',
    appId: '1:60097487307:ios:5a9bd57fdc83d2834c964e',
    messagingSenderId: '60097487307',
    projectId: 'campfood-6e14c',
    storageBucket: 'campfood-6e14c.firebasestorage.app',
    iosBundleId: 'com.campfood.campfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDauZ_xpjkquTq6TtunPQz6sPdqzv5nagU',
    appId: '1:60097487307:web:d917b2160f300da34c964e',
    messagingSenderId: '60097487307',
    projectId: 'campfood-6e14c',
    authDomain: 'campfood-6e14c.firebaseapp.com',
    storageBucket: 'campfood-6e14c.firebasestorage.app',
    measurementId: 'G-D4QR0J7JXK',
  );
}